include:
  - vdb/milvus.yaml

x-ragondin: &ragondin_template
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - /ray_mount/data:/app/data # PDF data for RAG
    - /ray_mount/model_weights:/app/model_weights # Model weights for RAG
    - ./ragondin:/app/ragondin # For dev mode
    - ${MILVUS_VOLUME_DIRECTORY:-./volumes}:/app/volumes
  network_mode: host
  env_file:
    - /ray_mount/.env
  shm_size: 10.24gb

  depends_on:
    - milvus

services:
  # GPU - default 
  ragondin:
    <<: *ragondin_template
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    profiles:
      - '' # Empty string gives default behavior (but does not run when cpu requested)

  # No GPU (docker compose --profile cpu up --build)
  ragondin-cpu:
    <<: *ragondin_template
    deploy: {}
    profiles:
      - 'cpu'
  
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    environment:
      - HUGGING_FACE_HUB_TOKEN
    ipc: "host"
    volumes:
      - ./vllm_cache:/root/.cache/huggingface
    command: >
      --model ${EMBEDDER_MODEL_NAME:-jinaai/jina-embeddings-v3}
      --api-key ${EMBEDDER_API_KEY,-EMPTY}
    ports:
      - 8000:8000
