include:
  - vdb/milvus.yaml
  - extern/infinity.yaml
  # - extern/vllm.yaml
  - ${CHAINLIT_DATALAYER_COMPOSE:-extern/dummy.yaml}
  - ${INDEXERUI_COMPOSE_FILE:-extern/dummy.yaml}

x-openrag: &openrag_template
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ${CONFIG_VOLUME:-./.hydra_config}:/app/.hydra_config
    - ${DATA_VOLUME:-./data}:/app/data
    - ${MODEL_WEIGHTS_VOLUME:-~/.cache/huggingface}:/app/model_weights # Model weights for RAG
    - ./openrag:/app/openrag # For dev mode
    - ${DB_VOLUME:-./db}:/app/db
    - /$SHARED_ENV:/ray_mount/.env # Shared environment variables
    - /ray_mount/logs:/app/logs
  ports:
    - ${APP_PORT:-8080}:${APP_iPORT:-8080}
    - ${RAY_DASHBOARD_PORT:-8265}:8265 # Disable when in cluster mode
  networks:
    default:
      aliases:
        - openrag
  env_file:
    - ${SHARED_ENV:-.env}
  shm_size: 10.24gb
  depends_on:
    - milvus


services:
  # GPU - default 
  openrag:
    <<: *openrag_template
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    profiles:
      - ''

  # No GPU
  openrag-cpu:
    <<: *openrag_template
    deploy: {}
    profiles:
      - 'cpu'