include:
  - vdb/milvus.yaml

x-ragondin: &ragondin_template
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ${CONFIG_VOLUME:-./.hydra_config}:/app/.hydra_config
    - ${DATA_VOLUME:-./data}:/app/data
    - ${MODEL_WEIGHTS_VOLUME:-~/.cache/huggingface}:/app/model_weights # Model weights for RAG
    - ./ragondin:/app/ragondin # For dev mode
    - ${DB_VOLUME:-./db}:/app/db
  ports:
    - ${APP_PORT:-8080}:${APP_iPORT:-8080}
    - ${RAY_DASHBOARD_PORT:-8265}:8265
  env_file:
    - ${SHARED_ENV:-.env}
  shm_size: 10.24gb
  depends_on:
    - milvus

services:
  # GPU - default 
  ragondin:
    <<: *ragondin_template
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    profiles:
      - ''

  # No GPU
  ragondin-cpu:
    <<: *ragondin_template
    deploy: {}
    profiles:
      - 'cpu'
  
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    environment:
      - HUGGING_FACE_HUB_TOKEN
    ipc: "host"
    volumes:
      - ${VLLM_CACHE:-/root/.cache/huggingface}:/root/.cache/huggingface
    command: >
      --model ${EMBEDDER_MODEL_NAME:-jinaai/jina-embeddings-v3}
      --trust-remote-code
    ports:
      - 8000:8000

  # # Conditional persistence service from submodule
  # chainlit-datalayer:
  #   build:
  #     context: ./services/chainlit-datalayer
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8001:8001