services:
  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
  chainlit-app:
    build: 
      dockerfile: Dockerfile
    volumes:
      - ./model_weights:/app/model_weights
      - ./data:/app/data # PDF data for RAG
    
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    
    depends_on:
      - qdrant

    
    command: >
      bash -c "
        uv run uvicorn api:app --host ${APP_HOST} --port ${APP_PORT}
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
