x-reranker: &reranker_template
  networks:
    default:
      aliases:
        - reranker
  volumes:
    - ${VLLM_CACHE:-/root/.cache/huggingface}:/app/.cache/huggingface # Model weights for RAG
  ports:
    - ${RERANKER_PORT:-7997}:${RERANKER_PORT:-7997}

services:
  reranker:
    <<: *reranker_template
    image: michaelf34/infinity
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    command: >
      v2
      --model-id ${RERANKER_MODEL:-Alibaba-NLP/gte-multilingual-reranker-base}
      --port ${RERANKER_PORT:-7997}
    profiles:
      - ''

  reranker-cpu:
    <<: *reranker_template
    image: michaelf34/infinity:latest-cpu
    deploy: {}
    command: >
      v2
      --engine optimum
      --model-id ${RERANKER_MODEL:-Alibaba-NLP/gte-multilingual-reranker-base}
      --port ${RERANKER_PORT:-7997}
    profiles:
      - 'cpu'