defaults:
  - _self_  # TODO: Silences the hydra version migration warning (PLEASE REVIEW FOR BREAKING CHANGES)
  - chunker: recursive_splitter #semantic_splitter
  - retriever: multiQuery
  - rag: ChatBotRag
  - llm: qwen

embedder:
  type: huggingface
  model_name: HIT-TMG/KaLM-embedding-multilingual-mini-v1
  
  
  # Alibaba-NLP/gte-Qwen2-1.5B-instruct
  # HIT-TMG/KaLM-embedding-multilingual-mini-v1
  # powerful multilingual model => More language => token's decomposed heavily => More to embed => this model is better than Alibaba NLP models

vectordb:
  host: ${oc.env:QDRANT_HOST, qdrant}
  port: ${oc.env:QDRANT_PORT, 6333}
  connector_name: qdrant
  collection_name: ${oc.env:COLLECTION_NAME, vdb_test}
  hybrid_mode: true

reranker:
  model_name: jinaai/jina-colbert-v2
  top_k: 7

grader:
  grade_documents: true

verbose:
  verbose: true
  level: DEBUG   # https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels

paths:
  prompts_dir: ${oc.env:PROMPTS_DIR, ../prompts}
  data_dir: ${oc.env:DATA_DIR, ../data}

prompt:
  rag_sys_pmpt: rag_sys_prompt_template.txt # rag_sys_pmpt_tmpl_ifa.txt
  context_pmpt_tmpl: contextualize_prompt_template.txt