# Continuous Integration workflow for OpenRAG
name: CI

on:
  # Disabled for now
  # push:
  #   branches: [main, dev]
  # pull_request:
  #   branches: [main, dev]
  workflow_dispatch: # Only allow manual triggering

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run linting with ruff
        run: |
          uv run ruff check .

      - name: Run formatting check with ruff
        run: |
          uv run ruff format --check .

      - name: Run Robot Framework tests
        run: |
          uv run robot tests/

  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (test)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: openrag:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
